version: '3.8'
services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    ports:
    - 8000:8000
    volumes:
    - .:/app
    depends_on:
    - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/zorma_db
    networks:
    - zorma_net
  db:
    image: postgres:13
    container_name: zorma_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zorma_db
    volumes:
    - postgres_data:/var/lib/postgresql/data
    ports:
    - 5432:5432
    networks:
    - zorma_net
volumes:
  postgres_data: {}
networks:
  zorma_net: {}